version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG:-True}
    depends_on:
      - db
    networks:
      - esda-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    depends_on:
      - backend
    networks:
      - esda-network

  db:
    image: postgis/postgis:15-3.3
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-esda_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esda-network

networks:
  esda-network:
    driver: bridge

volumes:
  postgres_data:
